
inp = input()
splitSen = input.split()
numWord = len(splitSen)
emojiWord = {
    "happy": "😆",
    "sad": "😢",
    "cry": "😢",
    "laugh": "😭",
    "dead": "🪦",
    "crying": "😭",
    "rofl": "🤣",
    "blow": "🌬️",
    "dog": "🐶",
    "cat": "🐱",
    "girl": "💁🏻‍♀️",
    "boy": "🧒🏻",
    "um": "🫥",
    "umm": "😶",
    "ummm": "🫤",
    "ummmm": "🦫",
    "erm": "🤓",
    "acktually": "☝️",
    "think": "🤔",
    "give": "👐",
    "gift": "🎁",
    "okat": "🙆🏻‍♀️",
    "no": "🙅🏻‍♀️",
    "say": "🗣️",
    "preach": "🗣️",
    "talk": "🗣️",
    "said": "🗣️",
    "talking": "🗣️",
    "love": "🩷",
    "like": "👍",
    "good": "👍",
    "bad": "👎",
    "boo": "👎",
    "james": "👴",
    "angry": "😡",
    "ugh": "🙄",
    "mad": "😠",
    "eat": "🍽️",
    "munch": "🦫",
    "yay": "🥳",
    "olivia": "😇",
    "hurt": "🤕",
    "sick": "🤒",
    "sleep": "😴",
    "snooze": "😴",
    "zzz": "😴",
    "yawn": "🥱",
    "shower": "🚿",
    "showering": "😶‍🌫️",
    "bath": "🛁",
    "anxious": "😣",
    "nervous": "😣",
    "mwah": "😘",
    "kiss": "😗",
    "fire": "🔥",
    "omg": "😱",
    "smirk": "😏",
    "ugh": "😒",
    "ughh": "🙄",
    "ughhh": "😕",
    "hate": "🤬",
    "alien": "👽",
    "hug": "🫂",
    "pray": "🙏",
    "wow": "😯",
    "woww": "😲",
    "wowww": "🤯",
    "agree": "🙂‍↕️",
    "iktr": "🙂‍↕️",
    "hear": "👂",
    "listen": "👂",
    "heard": "👂",
    "see": "👁️",
    "saw": "👀",
    "on": "🔛",
    "loop": "🔁",
    "time": "⏰"
}
for i in range(numWord):
    if splitSen(i).lower() in emojiWord:
        splitSen(i) = emojiWord[splitSen(i)]
print(splitSen)